 export const orders = [
    {
      id: "#1234",
      customer: "John Doe",
      email: "john@example.com",
      items: ["Pizza Margherita", "Coke"],
      total: "$25.99",
      status: "Delivered",
      time: "2:30 PM",
      date: "Today",
      address: "123 Main St, City",
    },
    {
      id: "#1235",
      customer: "Jane Smith",
      email: "jane@example.com",
      items: ["Chicken Burger", "Fries"],
      total: "$18.50",
      status: "Preparing",
      time: "2:25 PM",
      date: "Today",
      address: "456 Oak Ave, City",
    },
    {
      id: "#1236",
      customer: "Mike Johnson",
      email: "mike@example.com",
      items: ["Pasta Carbonara"],
      total: "$22.00",
      status: "Pending",
      time: "2:22 PM",
      date: "Today",
      address: "789 Pine St, City",
    },
    {
      id: "#1237",
      customer: "Sarah Wilson",
      email: "sarah@example.com",
      items: ["Caesar Salad", "Water"],
      total: "$15.75",
      status: "Out for Delivery",
      time: "2:18 PM",
      date: "Today",
      address: "321 Elm St, City",
    },
    {
      id: "#1238",
      customer: "Tom Brown",
      email: "tom@example.com",
      items: ["Fish & Chips", "Beer"],
      total: "$24.99",
      status: "Cancelled",
      time: "2:15 PM",
      date: "Today",
      address: "654 Maple Ave, City",
    },
  ];

 export const statusOptions = [
    "All",
    "Pending",
    "Preparing",
    "Out for Delivery",
    "Delivered",
    "Cancelled"
  ];
