export const featuredVideos = [
  {
    id: 1,
    embed: "E9SjN9mNo50",
     title: "ഷ വാ യിചിക്കൻ & വെ ജിറ്റബിൾ പുലാവ് /നമുക്ക് ഈസിയായി ഉണ്ടാക്കാം||കിടിലൻ ടേസ്റ്റിൽ ഒരു കിടിലൻ വിഭവം👌 //shavayi chiken&pulav//matbakhbayti/",
    description: "shavaya chiken &vejitabil pulav//",
    views: "89K",
    likes: "6.1K",
    duration: "06:34",
    category: "Cooking",
    difficulty: "Expert",
    thumbnail: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 2,
    embed: "9u6Wx_ukGB0",
    title: "ചെമ്മീൻ വെർമോസെല്ലി ബിരിയാണി 😋",
    description: "#chemmeenvermosellibiriyani #vermosellibiriyani",
    views: "89K",
    likes: "6.1K",
    duration: "8:49",
    category: "Biriyani",
    difficulty: "Medium",
    thumbnail: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 3,
    embed: "a5x0ctd00dU",
    title: "ബട്ടർ സ്കോച്ച് കേക്ക് 🥞||without oven|| simply made|| must try😊||",
    description: "Restaurant-quality at home",
    views: "203K",
    likes: "12.5K",
    duration: "7:55",
    category: "Cake",
    difficulty: "Advanced",
    thumbnail: "/placeholder.svg?height=300&width=500",
  },
]